'use client';
import {useEffect,useState} from 'react';
import {UserRound,CalendarDays,Activity,FileHeart,RefreshCw} from 'lucide-react';
import {apiFetch,openEcg} from '@/lib/api-client';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AiResult} from '@/components/ecg-ai';
import {analysisSchema} from '@/lib/ecg/schema';
export function CaseHistory({lang}:{lang:string}){
 const [rows,setRows]=useState<any[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[selected,setSelected]=useState<any>(null);
 const tr=(ru:string,en:string,uz:string)=>lang==='ru'?ru:lang==='uz'?uz:en;
 function load(){setLoading(true);setError('');apiFetch('/assessments').then(async r=>{const b:any=await r.json();if(!r.ok)throw Error(b.error);return b.assessments}).then(setRows).catch(()=>setError(tr('Не удалось загрузить историю','Unable to load history','Тарихни юклаб бўлмади'))).finally(()=>setLoading(false))}
 useEffect(load,[lang]);
 const stateText=(state:string)=>state==='stemi_omi'?tr('Подозрение на STEMI / OMI','Suspected STEMI / OMI','STEMI / OMI гумони'):state==='ischemia_risk'?tr('Риск ишемии','Ischemia risk','Ишемия хавфи'):state==='low_risk'?tr('Низкий риск','Low risk','Паст хавф'):tr('Оценка врача / уточнение','Clinical review','Шифокор баҳоси');
 return <section className="content-card"><div className="history-heading"><h2>{tr('История случаев','Case history','Ҳолатлар тарихи')}</h2><Button variant="outline" disabled={loading} onClick={load}><RefreshCw size={16}/>{tr('Обновить','Refresh','Янгилаш')}</Button></div>{error&&<p role="alert">{error}</p>}{loading?<p>…</p>:!rows.length?<p>{tr('Сохранённых оценок пока нет.','No saved assessments yet.','Сақланган баҳолар йўқ.')}</p>:<div className="history-grid">{rows.map(r=>{const state=r.ai_result?.analysis?.coronary_state;return <article key={r.id} className="history-card"><div className="history-patient"><UserRound size={22}/><h3>{r.patient_id||tr('ФИО не указано','Name not specified','Исм киритилмаган')}</h3></div><p className="history-date"><CalendarDays size={14}/>{new Date(r.created_at).toLocaleString(lang==='uz'?'uz-Cyrl':lang)}</p><span className={'history-state '+(state||'unknown')}>{stateText(state)}</span><div className="history-vitals"><span>{tr('Возраст','Age','Ёш')}: <b>{r.patient.age??'—'}</b></span><span>АД: <b>{r.patient.systolic??r.patient.sys??'—'}/{r.patient.diastolic??r.patient.dia??'—'}</b></span><span>SpO₂: <b>{r.patient.spo2??r.patient.spo??'—'}%</b></span></div><p className="history-summary">{r.ai_result?.analysis?.summary_for_clinician||r.finding||tr('Оценка сохранена','Assessment saved','Баҳолаш сақланди')}</p><div className="history-actions"><Button variant="outline" onClick={()=>setSelected(r)}><Activity size={16}/>{tr('Подробнее','Details','Батафсил')}</Button>{r.ecg_path&&<Button variant="outline" onClick={()=>openEcg(`/ecg/files/${r.ecg_path}`).catch(()=>setError(tr('Не удалось открыть ЭКГ','Unable to open ECG','ЭКГни очиб бўлмади')))}><FileHeart size={16}/>ЭКГ</Button>}</div></article>})}</div>}<Dialog open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="history-dialog"><DialogTitle>{selected?.patient_id||tr('Оценка пациента','Patient assessment','Бемор баҳоси')}</DialogTitle><DialogDescription>{selected?new Date(selected.created_at).toLocaleString():''}</DialogDescription>{selected&&<><p>{selected.patient.notes}</p>{selected.ai_result&&analysisSchema.safeParse(selected.ai_result.analysis).success?<AiResult result={selected.ai_result} lang={lang as 'ru'|'uz'|'en'}/>:<p>{selected.finding||tr('Оценка врача','Clinician assessment','Шифокор баҳоси')}</p>}</>}</DialogContent></Dialog></section>
}
