"use client";
import { useEffect, useMemo, useState } from "react";
import { Building2, CheckCheck, CircleAlert, Hospital, LoaderCircle, MapPin, Phone, Send, ShieldCheck, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import type { AnalysisEnvelope, Language } from "@/lib/ecg/schema";

type Center = {
  id: string; name: string; city: string; address: string; phone: string;
  emergency_phone?: string; latitude?: string | null; longitude?: string | null;
  pci_available?: number | boolean; accepting_patients?: number | boolean; manager_email?: string;
};
type CenterCopy = { lang: Language; onSent?: (center: Center) => void; patient?: Record<string, unknown>; patientId?: string; ecgFile?: File | null; finding?: string; ai?: AnalysisEnvelope | null; critical?: boolean };
const text = (lang: Language, en: string, uz: string, ru: string) => lang === "uz" ? uz : lang === "ru" ? ru : en;
const active = (value: unknown) => value === true || value === 1;
const errorText = (lang: Language, code: string) => ({
  directory_not_configured: text(lang, "Center directory is not configured yet. Apply the D1 migration first.", "Марказлар маълумотномаси ҳали созланмаган. Аввал D1 миграциясини қўлланг.", "Справочник центров ещё не настроен. Сначала примените миграцию D1."),
  transfer_not_configured: text(lang, "Secure transfer storage is not configured.", "Хавфсиз юбориш хранилиғи созланмаган.", "Защищённое хранилище передачи не настроено."),
  center_not_accepting: text(lang, "This center is currently not accepting patients. Choose another center.", "Бу марказ ҳозир бемор қабул қилмаяпти. Бошқа марказни танланг.", "Этот центр сейчас не принимает пациентов. Выберите другой."),
  center_not_found: text(lang, "The center is no longer available. Refresh the directory.", "Марказ топилмади. Маълумотномани янгиланг.", "Центр не найден. Обновите справочник."),
  sign_in_required: text(lang, "Sign in to use center accounts.", "Марказ аккаунтларидан фойдаланиш учун тизимга киринг.", "Войдите, чтобы использовать аккаунты центров."),
}[code] || text(lang, "The center service is temporarily unavailable.", "Марказ хизмати вақтинча ишламаяпти.", "Сервис центров временно недоступен."));

export function CenterChooser({ lang, onSent, patient, patientId, ecgFile, finding, ai, critical }: CenterCopy) {
  const [centers, setCenters] = useState<Center[]>([]), [centerId, setCenterId] = useState(""), [directoryError, setDirectoryError] = useState(""), [loading, setLoading] = useState(true), [consent, setConsent] = useState(false), [sending, setSending] = useState(false), [sent, setSent] = useState<{ id: string; name: string } | null>(null), [error, setError] = useState("");
  const selected = useMemo(() => centers.find(c => c.id === centerId), [centers, centerId]);
  useEffect(() => { let cancelled = false; setLoading(true); fetch("/api/centers", { cache: "no-store" }).then(async response => { const body = await response.json().catch(() => ({} as any)) as any; if (!response.ok) throw new Error(body.error || "directory_not_configured"); return body.centers || []; }).then(rows => { if (!cancelled) { setCenters(rows); setCenterId(rows[0]?.id || ""); setDirectoryError(""); } }).catch(e => { if (!cancelled) setDirectoryError(e.message); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, []);
  const tr = (en: string, uz: string, ru: string) => text(lang, en, uz, ru);
  async function send() {
    if (!selected || !ecgFile || !consent || sending) return;
    setSending(true); setError("");
    try {
      const form = new FormData(); form.set("image", ecgFile, ecgFile.name); form.set("context", JSON.stringify({ centerId: selected.id, transferConsent: true, patientId: patientId || undefined, patient, clinicianFinding: finding || undefined, gptSummary: ai?.analysis.summary_for_clinician, gptPriority: ai?.analysis.review_priority, analysisId: ai ? `${ai.model}:${ai.analyzed_at}` : undefined }));
      const response = await fetch("/api/handovers", { method: "POST", body: form }); const body = await response.json().catch(() => ({} as any)) as any; if (!response.ok) throw new Error(body.error || "transfer_not_configured");
      setSent({ id: body.handoverId, name: selected.name }); onSent?.(selected);
    } catch (e) { setError(errorText(lang, e instanceof Error ? e.message : "transfer_not_configured")); } finally { setSending(false); }
  }
  return <div className="center-chooser">
    <div className="destination-intro"><div className="center-hero-icon"><Hospital size={28}/></div><div><h3>{tr("Choose a receiving center", "Қабул қилувчи марказни танланг", "Выберите принимающий центр")}</h3><p>{tr("The selected center receives this patient handover in its manager account.", "Танланган марказ бемор топширувини менежер аккаунтида қабул қилади.", "Выбранный центр получит передачу пациента в аккаунте менеджера.")}</p></div></div>
    {loading ? <div className="center-loading"><LoaderCircle className="animate-spin"/> {tr("Loading verified centers…", "Тасдиқланган марказлар юкланмоқда…", "Загрузка проверенных центров…")}</div> : directoryError ? <div className="ai-error"><CircleAlert size={18}/><p>{errorText(lang, directoryError)}</p></div> : centers.length === 0 ? <div className="center-empty"><Building2 size={27}/><h3>{tr("No centers are published yet", "Ҳали марказлар эълон қилинмаган", "Центры ещё не опубликованы")}</h3><p>{tr("A center manager can create a profile from PCI centers.", "Марказ менежери PCI марказлар бўлимида профиль яратиши мумкин.", "Менеджер центра может создать профиль в разделе ЧКВ-центры.")}</p></div> : <>
      <label className="center-field">{tr("Receiving center", "Қабул қилувчи марказ", "Принимающий центр")}<Select value={centerId} onValueChange={setCenterId}><SelectTrigger className="w-full"><SelectValue placeholder={tr("Select a center", "Марказни танланг", "Выберите центр")}/></SelectTrigger><SelectContent>{centers.map(c => <SelectItem value={c.id} key={c.id}>{c.name} · {c.city}{active(c.accepting_patients) ? "" : ` · ${tr("not accepting", "қабул йўқ", "не принимает")}`}</SelectItem>)}</SelectContent></Select></label>
      {selected && <div className="center-detail"><div><b>{selected.name}</b><span><MapPin size={14}/>{selected.address}, {selected.city}</span><span><Phone size={14}/>{selected.emergency_phone || selected.phone}</span></div><div className="center-statuses"><span className={active(selected.pci_available) ? "status-on" : "status-off"}>{active(selected.pci_available) ? "PCI" : tr("No PCI", "PCI йўқ", "Без ЧКВ")}</span><span className={active(selected.accepting_patients) ? "status-on" : "status-off"}>{active(selected.accepting_patients) ? tr("Accepting", "Қабул қилади", "Принимает") : tr("Unavailable", "Мавжуд эмас", "Недоступен")}</span></div></div>}
      <div className="center-transfer-note"><ShieldCheck size={18}/><p>{tr("The transfer includes the patient details, clinician notes, GPT preliminary summary (if available) and the original ECG image.", "Топширув бемор маълумотлари, шифокор изоҳлари, GPT дастлабки хулосаси (мавжуд бўлса) ва асл ЭКГ тасвирини ўз ичига олади.", "Передача включает данные пациента, заметки врача, предварительное резюме GPT (если есть) и исходное изображение ЭКГ.")}</p></div>
      <label className="ai-consent center-consent"><Checkbox checked={consent} disabled={sending || !!sent} onCheckedChange={v => setConsent(v === true)}/><span>{tr("I confirm this is an authorized clinical handover and the receiving center may view the patient information and ECG.", "Мен бу ваколатли клиник топширув эканини ва қабул қилувчи марказ бемор маълумотлари ҳамда ЭКГни кўриши мумкинлигини тасдиқлайман.", "Я подтверждаю, что это разрешённая клиническая передача и принимающий центр может просматривать данные пациента и ЭКГ.")}</span></label>
      {error && <div className="ai-error"><CircleAlert size={18}/><p>{error}</p></div>}{sent && <div className="ai-success"><CheckCheck size={18}/><span>{tr(`Sent to ${sent.name}. Handover ID ${sent.id.slice(0, 8)}.`, `${sent.name} марказига юборилди. Топширув ID ${sent.id.slice(0, 8)}.`, `Отправлено в ${sent.name}. ID передачи ${sent.id.slice(0, 8)}.`)}</span></div>}
      <Button className="send-center-button" disabled={!selected || !active(selected.accepting_patients) || !ecgFile || !consent || sending || !!sent} onClick={send}>{sending ? <LoaderCircle className="animate-spin"/> : <Send/>}{sending ? tr("Sending securely…", "Хавфсиз юборилмоқда…", "Безопасная отправка…") : tr("Send patient + ECG", "Бемор + ЭКГни юбориш", "Отправить пациента + ЭКГ")}</Button>
      {critical && <p className="center-urgent-note"><CircleAlert size={15}/>{tr("If this is an emergency, call the receiving center while sending. Do not delay care for the app.", "Шошилинч ҳолатда илова учун ёрдамни кечиктирманг; юбориш жараёнида марказга қўнғироқ қилинг.", "При экстренной ситуации звоните в центр во время отправки. Не задерживайте помощь из-за приложения.")}</p>}
    </>}
  </div>;
}

export function CenterDirectory({ lang, centers: label }: { lang: Language; centers?: string }) {
  const tr = (en: string, uz: string, ru: string) => text(lang, en, uz, ru);
  const [rows, setRows] = useState<Center[]>([]), [handovers, setHandovers] = useState<Record<string, any[]>>({}), [loading, setLoading] = useState(true), [error, setError] = useState(""), [saved, setSaved] = useState(false), [editingId, setEditingId] = useState<string | null>(null), [form, setForm] = useState({ name: "", city: "", address: "", phone: "", emergencyPhone: "", latitude: "", longitude: "", pciAvailable: true, acceptingPatients: true });
  const load = () => { setLoading(true); fetch("/api/centers?mine=1", { cache: "no-store" }).then(async r => { const body = await r.json().catch(() => ({} as any)) as any; if (!r.ok) throw new Error(body.error || "directory_not_configured"); return body.centers || []; }).then(setRows).catch(e => setError(errorText(lang, e.message))).finally(() => setLoading(false)); };
  useEffect(load, [lang]);
  const update = (key: string, value: string | boolean) => setForm(f => ({ ...f, [key]: value }));
  async function create() { setError(""); setSaved(false); const endpoint = editingId ? "/api/centers/" + editingId : "/api/centers"; const method = editingId ? "PUT" : "POST"; const r = await fetch(endpoint, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const body = await r.json().catch(() => ({} as any)) as any; if (!r.ok) { setError(errorText(lang, body.error || "directory_not_configured")); return; } setSaved(true); setEditingId(null); setForm({ name: "", city: "", address: "", phone: "", emergencyPhone: "", latitude: "", longitude: "", pciAvailable: true, acceptingPatients: true }); load(); }
  async function loadHandovers(id: string) { const r = await fetch(`/api/centers/${id}/handovers`, { cache: "no-store" }); const body = await r.json().catch(() => ({} as any)) as any; if (r.ok) setHandovers(h => ({ ...h, [id]: body.handovers || [] })); else setError(errorText(lang, body.error || "directory_not_configured")); }
  return <section className="content-card center-directory"><div className="center-directory-heading"><div><Building2 className="text-teal-700" size={28}/><h2>{label || tr("PCI center accounts", "PCI марказ аккаунтлари", "Аккаунты ЧКВ-центров")}</h2><p>{tr("Managers maintain location, phone numbers and live acceptance status. Clinicians can only select centers marked as accepting.", "Менежерлар жойлашув, телефон ва қабул ҳолатини бошқаради. Шифокорлар фақат қабул қилаётган марказларни танлайди.", "Менеджеры поддерживают адрес, телефоны и статус приёма. Врачи могут выбирать только принимающие центры.")}</p></div><span className="prototype"><ShieldCheck size={14}/>{tr("Manager-controlled", "Менежер назоратида", "Под управлением менеджера")}</span></div>
    {loading ? <div className="center-loading"><LoaderCircle className="animate-spin"/> {tr("Loading your centers…", "Марказларингиз юкланмоқда…", "Загрузка ваших центров…")}</div> : error ? <div className="ai-error"><CircleAlert size={18}/><p>{error}</p></div> : <>
      {rows.map(c => <div className="managed-center" key={c.id}><div className="managed-center-top"><div><h3>{c.name}</h3><p><MapPin size={14}/>{c.address}, {c.city}</p><p><Phone size={14}/>{c.emergency_phone || c.phone}</p></div><div className="center-statuses"><span className={active(c.pci_available) ? "status-on" : "status-off"}>{active(c.pci_available) ? "PCI" : tr("No PCI", "PCI йўқ", "Без ЧКВ")}</span><span className={active(c.accepting_patients) ? "status-on" : "status-off"}>{active(c.accepting_patients) ? tr("Accepting patients", "Бемор қабул қилади", "Принимает пациентов") : tr("Not accepting", "Қабул йўқ", "Не принимает")}</span></div></div><div className="managed-center-actions"><Button variant="outline" onClick={() => loadHandovers(c.id)}><UserRound size={15}/>{tr("View incoming handovers", "Келган топширувлар", "Входящие передачи")} {handovers[c.id] ? `(${handovers[c.id].length})` : ""}</Button><Button variant="outline" onClick={() => { setEditingId(c.id); setForm({ name: c.name, city: c.city, address: c.address, phone: c.phone, emergencyPhone: c.emergency_phone || c.phone, latitude: c.latitude || "", longitude: c.longitude || "", pciAvailable: active(c.pci_available), acceptingPatients: active(c.accepting_patients) }); }}>{tr("Edit profile", "Профильни таҳрирлаш", "Изменить профиль")}</Button><span className="managed-id">{tr("Manager account", "Менежер аккаунти", "Аккаунт менеджера")}</span></div>{handovers[c.id] && <div className="handover-list">{handovers[c.id].length ? handovers[c.id].map(h => <div className="handover-row" key={h.id}><div><b>{h.patient?.patientId || tr("Patient handover", "Бемор топшируви", "Передача пациента")}</b><span>{new Date(h.created_at).toLocaleString(lang === "uz" ? "uz-Cyrl" : lang)} · {h.clinician_email}</span><p>{tr("Status", "Ҳолат", "Статус")}: {h.status} · {tr("ECG image", "ЭКГ тасвири", "Изображение ЭКГ")}</p></div><a href={`/api/handovers/${h.id}/ecg`} target="_blank" rel="noreferrer">{tr("Open ECG", "ЭКГни очиш", "Открыть ЭКГ")}</a></div>) : <p className="clinical-note">{tr("No patient handovers yet.", "Ҳали бемор топширувлари йўқ.", "Передач пациентов пока нет.")}</p>}</div>}</div>)}
      {!rows.length && <div className="center-empty"><Building2 size={28}/><h3>{tr("Create your center account", "Марказ аккаунтингизни яратинг", "Создайте аккаунт центра")}</h3><p>{tr("The signed-in user becomes the center manager and can update availability later.", "Тизимга кирган фойдаланувчи марказ менежери бўлади ва кейин қабул ҳолатини ўзгартира олади.", "Вошедший пользователь становится менеджером центра и сможет менять статус приёма.")}</p></div>}
      <div className="manager-form"><h3>{tr("Center profile", "Марказ профили", "Профиль центра")}</h3><div className="manager-grid"><label>{tr("Center name", "Марказ номи", "Название центра")}<Input value={form.name} onChange={e => update("name", e.target.value)} placeholder="Central Cardiology Center"/></label><label>{tr("City", "Шаҳар", "Город")}<Input value={form.city} onChange={e => update("city", e.target.value)} placeholder="Tashkent"/></label><label>{tr("Address", "Манзил", "Адрес")}<Input value={form.address} onChange={e => update("address", e.target.value)} placeholder="Street, building"/></label><label>{tr("Main phone", "Асосий телефон", "Основной телефон")}<Input value={form.phone} onChange={e => update("phone", e.target.value)} placeholder="+998 71 000 00 00"/></label><label>{tr("Emergency / PCI line", "Шошилинч / PCI рақами", "Экстренная / линия ЧКВ")}<Input value={form.emergencyPhone} onChange={e => update("emergencyPhone", e.target.value)} placeholder="+998 90 000 00 00"/></label><label>{tr("Latitude (optional)", "Кенглик (ихтиёрий)", "Широта (необязательно)")}<Input value={form.latitude} onChange={e => update("latitude", e.target.value)} placeholder="41.3111"/></label><label>{tr("Longitude (optional)", "Узунлик (ихтиёрий)", "Долгота (необязательно)")}<Input value={form.longitude} onChange={e => update("longitude", e.target.value)} placeholder="69.2797"/></label></div><div className="manager-toggles"><label><Checkbox checked={form.pciAvailable} onCheckedChange={v => update("pciAvailable", v === true)}/>{tr("PCI procedure available", "PCI амалиёти мавжуд", "Доступно ЧКВ")}</label><label><Checkbox checked={form.acceptingPatients} onCheckedChange={v => update("acceptingPatients", v === true)}/>{tr("Accepting patients now", "Ҳозир бемор қабул қилади", "Принимаем пациентов сейчас")}</label></div><Button disabled={!form.name || !form.city || !form.address || !form.phone || !form.emergencyPhone} onClick={create}><Building2 size={16}/>{editingId ? tr("Save profile changes", "Профиль ўзгаришларини сақлаш", "Сохранить изменения") : tr("Create center account", "Марказ аккаунтини яратиш", "Создать аккаунт центра")}</Button>{saved && <span className="saved-inline"><CheckCheck size={15}/>{tr("Center profile created.", "Марказ профили яратилди.", "Профиль центра создан.")}</span>}</div>
    </>}</section>;
}
