'use client';
import type {EcgAnalysis,Language} from '@/lib/ecg/schema';
import {HeartPulse,TriangleAlert,ShieldCheck,ScanLine,Ambulance,Activity,PhoneCall,Stethoscope,Clock3} from 'lucide-react';
export function CoronaryState({analysis:a,lang,reveal=false}:{analysis:EcgAnalysis;lang:Language;reveal?:boolean}){
 const tr=(ru:string,en:string,uz:string)=>lang==='ru'?ru:lang==='uz'?uz:en;
 const state=a.coronary_state;
 if(state===undefined)return null; // Older assessments are not retrospectively reclassified.
 const title=state==='stemi_omi'?tr('Подозрение на STEMI / OMI (коронарную окклюзию)','Suspected STEMI / OMI (coronary occlusion)','STEMI / OMI (коронар окклюзия) гумони'):state==='ischemia_risk'?tr('Риск ишемии','Ischemia risk','Ишемия хавфи'):state==='low_risk'?tr('Низкий риск / без острых изменений ЭКГ','Low risk / no acute ECG changes','Паст хавф / ўткир ЭКГ ўзгаришлари йўқ'):tr('Недостаточно данных для коронарной оценки','Insufficient data for coronary assessment','ЭКГ баҳолаш учун етарли эмас');
 const steps=state==='stemi_omi'?[tr('Реанимационная подготовка и мониторинг.','Resuscitation readiness and monitoring.','Реанимацияга тайёргарлик ва мониторинг.'),tr('Срочно связаться с PCI-центром и организовать экстренную транспортировку по локальному маршруту.','Contact a PCI center urgently and arrange emergency transport through the local pathway.','PCI марказ билан зудликда боғланиш ва маҳаллий тартибда шошилинч транспортировка.')]:state==='ischemia_risk'?[tr('Дополнительные отведения: V3R–V4R при подозрении на поражение правого желудочка; V7–V9 при подозрении на задний инфаркт или окклюзию с неубедительной стандартной ЭКГ.','Additional leads: V3R–V4R for suspected RV involvement; V7–V9 for suspected posterior infarction or occlusion with inconclusive standard ECG.','Қўшимча V3R–V4R — ўнг қоринча шикастланиши гумонида; V7–V9 — орқа инфаркт ёки ноаниқ стандарт ЭКГ билан окклюзия гумонида.'),tr('Срочная телеконсультация кардиолога. Не задерживать экстренную помощь ради консультации.','Urgent cardiology teleconsultation. Do not delay emergency care for consultation.','Кардиолог билан тезкор телеконсультация. Шошилинч ёрдамни кечиктирманг.')]:state==='low_risk'?[tr('Стандартная помощь по состоянию пациента и динамическое наблюдение.','Standard care based on clinical condition and ongoing observation.','Бемор ҳолатига мос стандарт ёрдам ва динамик кузатув.'),tr('Повторная оценка при симптомах или ухудшении. Нормальная ЭКГ не исключает ОКС.','Reassess with symptoms or deterioration. A normal ECG does not exclude ACS.','Симптомлар ёки ёмонлашишда қайта баҳолаш. Нормал ЭКГ ЎКСни истисно қилмайди.')]:[tr('Уточнить клинические данные и повторить ЭКГ, если запись недостаточно информативна. Срочность помощи определяется состоянием пациента.','Clarify clinical information and repeat ECG if the recording is inadequate. Clinical condition determines urgency.','Сифатли ЭКГни такрорланг. Ёрдам шошилинчлиги бемор ҳолатига боғлиқ.')];
 const Icon=state==='stemi_omi'?HeartPulse:state==='ischemia_risk'?TriangleAlert:state==='low_risk'?ShieldCheck:ScanLine;
 const actionIcons=state==='stemi_omi'?[Activity,Ambulance]:state==='ischemia_risk'?[ScanLine,PhoneCall]:state==='low_risk'?[Stethoscope,Clock3]:[ScanLine];
 const card=<section key={state||'unknown'} className={'coronary-state '+(state||'unknown')} aria-label={title}><div className="coronary-state-heading"><span className="coronary-state-icon"><Icon size={30} strokeWidth={1.8} aria-hidden="true"/></span><div><small>{tr('ОСНОВНОЕ ЗАКЛЮЧЕНИЕ ИИ · ПРЕДВАРИТЕЛЬНО','MAIN AI ASSESSMENT · PRELIMINARY','АСОСИЙ AI ХУЛОСАСИ · ДАСТЛАБКИ')}</small><h3>{title}</h3></div></div><p>{a.priority_reason}</p><b>{tr('Тактика врача','Physician actions','Шифокор тактикаси')}</b><ul>{steps.map((s,i)=>{const ActionIcon=actionIcons[i];return <li key={s}><ActionIcon size={20} aria-hidden="true"/><span>{s}</span></li>})}</ul></section>;
 return reveal?<div className="coronary-flip"><div className="coronary-flip-inner"><div className="coronary-flip-front" aria-hidden="true"><HeartPulse size={42}/></div><div className="coronary-flip-back">{card}</div></div></div>:card;
}
